project:
  type: website
  output-dir: docs

website:
  title: "Pierre Vernier"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu:
        - text: Disturbance mapping
          href: http://nwb.ualberta.ca
        - text: Northwest Boreal assessment
          href: http://nwb.ualberta.ca
        - text: Pan-boreal Assessment
          href: http://pba.ualberta.ca
        - text: CASFRI
          href: https://casfri.github.io/CASFRI/
        - text: SFI conservation tool
          href: https://borealbirds.ualberta.ca/2020/12/03/conservation-value-assessment-tool
        - text: Intactness paper
          href: https://github.com/prvernier/intactness
        - text: Surrogates paper
          href: https://github.com/prvernier/surrogates
      - text: "Apps"
        menu:
        - text: Geopackage Creator
          href: https://github.com/beaconsproject/geopackage_creator
        - text: Disturbance Explorer
          href: https://github.com/beaconsproject/disturbance_explorer
        - text: Test dashboard
          href: https://prvernier.github.io/dashboards/test/
        - text: Geopackage Explorer
          href: https://prvernier.github.io/apps/gpkg-viewer/
        - text: BC Atlas
          href: https://prvernier.github.io/apps/bc-atlas/
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true