project:
  type: website
  output-dir: docs

website:
  title: "Pierre Vernier"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu:
        - text: Disturbance mapping
          href: https://github.com/beaconsproject/disturbance_mapping
        - text: Caribou workbook
          href: https://github.com/beaconsproject/caribou_workbook
      - text: "Apps"
        menu:
        - text: Caribou apps
          href: https://github.com/beaconsproject/caribou_apps
        - text: Caribou dashboard
          href: https://github.com/beaconsproject/caribou_dashboard
        - text: Geopackage creator
          href: https://github.com/beaconsproject/geopackage_creator
        - text: Disturbance explorer
          href: https://github.com/beaconsproject/disturbance_explorer
      - text: "Other"
        menu:
        - text: Parcelles
          href: https://prvernier.github.io/parcelles.html
        - text: Parcelles (new version)
          href: https://prvernier.github.io/levier/dashboard.html
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true