project:
  type: website
  output-dir: docs

website:
  title: "Pierre Vernier"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu:
        - text: Disturbance mapping
          href: http://nwb.ualberta.ca
        - text: Pan-boreal assessment
          href: http://pba.ualberta.ca
        - text: CASFRI
          href: https://github.com/CASFRI/CASFRI
        - text: SFI conservation tool
          href: https://borealbirds.ualberta.ca/2020/12/03/conservation-value-assessment-tool
        - text: Intactness paper
          href: https://github.com/prvernier/intactness
        - text: Surrogates paper
          href: https://github.com/prvernier/surrogates
      - text: "Apps"
        menu:
        - text: Disturbance explorer
          href: https://github.com/beaconsproject/disturbance_explorer
        - text: Test dashboard
          href: https://github.com/prvernier/dashboards/test
        - text: Geopackage Explorer
          href: https://github.com/prvernier/apps/gpkg-viewer
        - text: BC Atlas
          href: https://github.com/prvernier/apps/bc-atlas
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true