---
title: "About"
date: "`r format(Sys.time(), '%d %B %Y')`"
---

# Welcome!

I am a landscape ecologist with the [Department of Renewable Resources](http://www.rr.ualberta.ca) at the University of Alberta. My research interests include biodiversity monitoring, systematic conservation planning, and species distribution modelling. I am a member of the [BEACONs Project](http://www.beaconsproject.ca/), which is developing a scientific framework for comprehensive conservation planning through the development and application of leading-edge conservation science that includes consideration of both protected areas and lands managed for other values.

In addition to research, I enjoy trail running in the coastal mountains and forests of British Columbia and Washington State as well as the Jura and Alps in France.

### Academic interests

  * Landscape ecology
  * Conservation planning
  * Biodiversity monitoring
  * Species distribution modelling

### Academic degrees

  * MSc 1995, University of British Columbia
  * BA 1983, University of British Columbia
  