---
title: "Climate Resilience Metrics"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: "Pierre Vernier"
output:
  html_document:
    keep_md: false
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
      number_sections: true
---

<br>

How can we assess landscape-level vulnerability to climate change?

Incorporating climate resilience and connectivity into systematic conservation planning in the boreal forest. We review the metrics used by the AdaptWest [Climate Resilience Data Explorer (CRDE)](https://adaptwest.shinyapps.io/climate-resilience-data-explorer/) and consider some adaptation that would make it more suitable for regional scale planning. As a case study we use the KDTT planning region plus a 100km buffer. The AdaptWest app considers eight metrics and summarizes them in a starplot. We review each metric and discuss its limitation, and provide alternatives if any exist.

The CRDE app calculates the 8 metrics for a user selected ecoregion and its intersecting watersheds. The ecoregions uses the uses ecoregions. The watershed maps uses the WSC SSDA dataset in Canada and the HUC level 8 watersheds (?) in the USA. In our examples, we will use the Kaska Dena Territorial Boundary (KDTT) + 100km buffer as a study region.

---

# Climate dissimilarity

## Existing map

The map below shows the existing climate dissimilarity map clipped to the study region. The dataset can be downloaded from:

- https://adaptwest.databasin.org/pages/climatic-dissimilarity/

```{r echo=TRUE, message=FALSE, warning=FALSE}


## Custom map

We replicated the methods used to create the climate dissimilarity maps using same bioclimatic variable but clipped to our study region.

---

# Climatic velocity

## Forward climatic velocity

## Backward climatic velocity

---

# Topodiversity

---

# Biotic velocity

---

# Climate connectivity

---

# Soil carbon

---

# Intactness

The inverse of landuse intensity.

### Forest Landscape Intactness Index

From the website: "The Forest Landscape Integrity Index integrates data on observed and inferred forest pressures and lost forest connectivity to generate the first globally-consistent, continuous index of forest integrity as determined by degree of anthropogenic modification. This is the first measure of ecological integrity for all the world’s forests. The study brought together 47 forest experts from across the world to apply recent developments in cloud computing and large new datasets."

  - Data years:
  - References: Grantham et al. 2020
  - Website: https://www.forestlandscapeintegrity.com/home


### Global Intact Forest Landscapes

The global Intact Forest Landscapes maps describe large unbroken expanses of natural ecosystems for the years 2000, 2013 and 2016 within areas of current forest extent, without signs of significant human activity, and having an area of at least 500 km2. The forest zone boundary was defined using a global tree canopy cover dataset (MODIS 500m) and included all areas with a tree canopy cover &gt; 20% in the year 2000. The global IFL maps were created using maps of human settlements and transportation networks and a global coverage of high spatial resolution satellite imagery (Landsat 5 & 7, 30m).

  - Data years: 2000, 2013, 2016
  - References: Potapov et al. 2008, 2017
  - Website: http://www.intactforests.org/

---

### Canada Intact Forest Landscapes

The Intact Forest Landscapes maps (CIFL 2000 and CIFL 2013; ) depict Canada's remaining forest landscape fragments for the years 2000 and 2013. The datasets use specified size thresholds of 5,000 hectares for boreal regions and 1,000 hectares for temperate forest regions. The map was produced using (i) existing datasets describing major anthropogenic changes/disturbances (e.g., roads, other linear features, reservoirs) to exclude large areas influenced by human activities and (ii) satellite imagery (Landsat 5 and 7, 30m) to identify finer scale anthropogenic disturbances (e.g., cutblocks, cutlines) within candidate intact forest landscapes.

  - Data years: 2000, 2013
  - References: Lee 2006, Smith and Cheng 2016
  - Website: https://databasin.org/datasets/a1d3559466574164a4f99be6a2445cea

---

### Human Footprint (Canada)

The Human Footprint maps measures the human influence on the earth's land surface in terms of a Human Influence Index (HII) normalized by biome and realm. Human Footprint values range from 1 to 50. Older version: The Human Footprint (HFP) map measures the human influence on the earth's land surface in terms of a Human Influence Index (HII) normalized by biome and realm. Human Footprint values range from 1 to 100. A score of 1 indicates that the grid cell is part of the 1% least influenced area in its biome. The HII map was created from nine global data layers covering human population pressure (population density, population settlements), human land use and infrastructure (built up areas, nighttime lights, land use/land cover), and human access (coastlines, roads, railroads, navigable rivers). A third map product, The Last of the Wild, highlights the remaining 10% least influenced areas by biome or ecoregion. Version 2 of the maps were published in 2005 by the Wildlife Conservation Society (WCS) and Center for International Earth Science Information Network (CIESIN).

  - Data years: 1993, 2009
  - References: Sanderson et al. 2002, Venter et al. 2016a, 2016b
  - Website: http://datadryad.org/resource/doi:10.5061/dryad.052q5

### Global Human Modification

The global Human Modification map provides a cumulative measure of human modification of terrestrial lands across the globe at a 1-km2 resolution. It is a continuous 0-1 metric that reflects the proportion of a landscape modified based on modeling the physical extents of 13 anthropogenic stressors and their estimated impacts using spatially-explicit global datasets with a median year of 2016.

  - Data years: 2015
  - References: Kennedy et al. 2019
  - Website: https://figshare.com/articles/Global_Human_Modification/7283087

### Low Impact Areas

The Low Impact Areas dataset uses open-access, frequently updated data sets on terrestrial human impacts (human population density, built-up area, cropland, livestock, forest cover change, roads, night-time lights) to create a new categorical map of global human influence ("Low Impact Areas" and "Very Low Impact Areas") at a 1-km2 resolution.

  - Data years: 2015
  - References: Jacobson et al. 2019
  - Website: https://datadryad.org/stash/dataset/doi:10.5061/dryad.z612jm67g

---

### Canada Human Access

Global Forest Watch Canada's Human Access dataset is current to circa 2010. Human access is the combined land surface anthropogenic disturbances caused mainly by industrial activities, which include, but are not limited to, roads, mines, clearcuts, wellsites, pipelines, transmission lines, and agricultural clearings. All disturbances (i.e., access) were buffered by 500 metres. The Canada Access 2010 dataset was created as the initial step in creating the Canada IFL maps.

  - Data years: 2010
  - References: Lee and Cheng 2014
  - Website: https://globalforestwatch.ca/sites/gfwc/files/data/20140109B_Canada_Access_2010_metadata.html

---

## Canada Datasets

### Annual Mapping of Large Forest Disturbances

Annual mapping of large forest disturbances in Canada (Guindon et al. 2014). Annual mapping of large forest disturbances across Canada's forests using 250m MODIS imagery from 2000 to 2011. At total of 22 raster maps were generated representing fractional change and disturbance type. Fractional change is mapped as a continuous variable at the pixel level. Disturbance types were classified as no-change, fire, harvesting, or flooding.
  
  - Data years: 2000-2011
  - References: Guindon et al. 2014
  - Website: http://www.nrcresearchpress.com/doi/abs/10.1139/cjfr-2014-0229#.Wcu9msiGPRZ (See Supplementary data)

### Canada Landsat Disturbance

Canada Landsat Disturbance (CanLaD) 2017. This dataset includes a set of raster maps in which areas affected by fire or by harvest from 1984 to 2015 are identified at the level of individual 30m pixels on the Landsat grid. Details of the product development can be found in Guindon et. al. (2017, 2018).

  - Data years: 1984-2015
  - References: Guindon et al. 2017, 2018
  - Website: https://open.canada.ca/data/en/dataset/add1346b-f632-4eb9-a83d-a662b38655ad

### Satellite forest monitoring

Satellite forest monitoring in Canada. Online satellite-derived forest change map for Canada with information on the amount, type, and rates of disturbances from 1985-2011. The maps were developed using Landsat imagery at a resolution of 30m and estimate change type as being fire, infrastructure, harvest, or untyped.
  
  - Data years: 1985-2011
  - References: White et al. 2017
  - Website: http://forests.foundryspatial.com/

---

# References


