---
title: "Conservation Planning Datasets"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: "Pierre Vernier"
output:
  html_document:
    keep_md: false
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
      number_sections: true
---

<br>

Intactness and disturbance datasets are increasingly used by conservation planners to design and evaluate protected areas. This page describes existing global and regional datasets that measure intactness (e.g., intact forest landscapes) or cumulative disturbances (e.g., human footprint maps) for use in the boreal region of North America.

  * Detailed characteristics of some of the datasets can be found [here](https://docs.google.com/spreadsheets/d/17x_a3f5QkyALlC7vYdq61wou_UAYvwR2ViyIFDHrsBg/edit?usp=sharing).

---

# Protected Areas

---

# Wilderness and Intact Areas

## Global Datasets

### Forest Landscape Intactness Index

From the website: "The Forest Landscape Integrity Index integrates data on observed and inferred forest pressures and lost forest connectivity to generate the first globally-consistent, continuous index of forest integrity as determined by degree of anthropogenic modification. This is the first measure of ecological integrity for all the world’s forests. The study brought together 47 forest experts from across the world to apply recent developments in cloud computing and large new datasets."

  - Data years:
  - References: Grantham et al. 2020
  - Website: https://www.forestlandscapeintegrity.com/home


### Global Intact Forest Landscapes

The global Intact Forest Landscapes maps describe large unbroken expanses of natural ecosystems for the years 2000, 2013 and 2016 within areas of current forest extent, without signs of significant human activity, and having an area of at least 500 km2. The forest zone boundary was defined using a global tree canopy cover dataset (MODIS 500m) and included all areas with a tree canopy cover &gt; 20% in the year 2000. The global IFL maps were created using maps of human settlements and transportation networks and a global coverage of high spatial resolution satellite imagery (Landsat 5 & 7, 30m).

  - Data years: 2000, 2013, 2016
  - References: Potapov et al. 2008, 2017
  - Website: http://www.intactforests.org/

### Frontier Forests

The Forest Frontiers map was the first attempt to create a global map of the remaining large, ecologically intact, and relatively undisturbed natural forest landscapes. The map shows where the last remaining large areas of forest remains and provides an assessment of the degree of threat (low or no threat, medium or high threat, unassessed for threat). The maps were created from readily-accessible, but variable, ancillary information such as roads, and numerous experts provided advice and reviews. Unlike the other more recent approaches, Frontier Forests did not use consistent and more recent data sources such as satellite imagery. The Forest Frontiers map was published in 1997 by World Resources Institute.

  - Data years: 1996
  - References: Bryant et al. 1997
  - Website: http://www.wri.org/publication/last-frontier-forests

---

## Canada Datasets

### Canada Intact Forest Landscapes

The Intact Forest Landscapes maps (CIFL 2000 and CIFL 2013; ) depict Canada's remaining forest landscape fragments for the years 2000 and 2013. The datasets use specified size thresholds of 5,000 hectares for boreal regions and 1,000 hectares for temperate forest regions. The map was produced using (i) existing datasets describing major anthropogenic changes/disturbances (e.g., roads, other linear features, reservoirs) to exclude large areas influenced by human activities and (ii) satellite imagery (Landsat 5 and 7, 30m) to identify finer scale anthropogenic disturbances (e.g., cutblocks, cutlines) within candidate intact forest landscapes.

  - Data years: 2000, 2013
  - References: Lee 2006, Smith and Cheng 2016
  - Website: https://databasin.org/datasets/a1d3559466574164a4f99be6a2445cea

---

# Cumulative Disturbances

## Global Datasets

### Human Footprint

The Human Footprint maps measures the human influence on the earth's land surface in terms of a Human Influence Index (HII) normalized by biome and realm. Human Footprint values range from 1 to 50. Older version: The Human Footprint (HFP) map measures the human influence on the earth's land surface in terms of a Human Influence Index (HII) normalized by biome and realm. Human Footprint values range from 1 to 100. A score of 1 indicates that the grid cell is part of the 1% least influenced area in its biome. The HII map was created from nine global data layers covering human population pressure (population density, population settlements), human land use and infrastructure (built up areas, nighttime lights, land use/land cover), and human access (coastlines, roads, railroads, navigable rivers). A third map product, The Last of the Wild, highlights the remaining 10% least influenced areas by biome or ecoregion. Version 2 of the maps were published in 2005 by the Wildlife Conservation Society (WCS) and Center for International Earth Science Information Network (CIESIN).

  - Data years: 1993, 2009
  - References: Sanderson et al. 2002, Venter et al. 2016a, 2016b
  - Website: http://datadryad.org/resource/doi:10.5061/dryad.052q5

### Global Human Modification

The global Human Modification map provides a cumulative measure of human modification of terrestrial lands across the globe at a 1-km2 resolution. It is a continuous 0-1 metric that reflects the proportion of a landscape modified based on modeling the physical extents of 13 anthropogenic stressors and their estimated impacts using spatially-explicit global datasets with a median year of 2016.

  - Data years: 2015
  - References: Kennedy et al. 2019
  - Website: https://figshare.com/articles/Global_Human_Modification/7283087

### Low Impact Areas

The Low Impact Areas dataset uses open-access, frequently updated data sets on terrestrial human impacts (human population density, built-up area, cropland, livestock, forest cover change, roads, night-time lights) to create a new categorical map of global human influence ("Low Impact Areas" and "Very Low Impact Areas") at a 1-km2 resolution.

  - Data years: 2015
  - References: Jacobson et al. 2019
  - Website: https://datadryad.org/stash/dataset/doi:10.5061/dryad.z612jm67g

---

## Canada Datasets

### Canada Human Access

Global Forest Watch Canada's Human Access dataset is current to circa 2010. Human access is the combined land surface anthropogenic disturbances caused mainly by industrial activities, which include, but are not limited to, roads, mines, clearcuts, wellsites, pipelines, transmission lines, and agricultural clearings. All disturbances (i.e., access) were buffered by 500 metres. The Canada Access 2010 dataset was created as the initial step in creating the Canada IFL maps.

  - Data years: 2010
  - References: Lee and Cheng 2014
  - Website: https://globalforestwatch.ca/sites/gfwc/files/data/20140109B_Canada_Access_2010_metadata.html


### Boreal Ecosystem Anthropogenic Disturbance

Boreal ecosystem anthropogenic disturbance (BEAD) layers for Canada . A vector disturbance dataset of unbuffered individual linear and polygonal disturbance types covering 51 caribou ranges in Canada. The dataset is based on 2008-2010 Landsat 5 imagery and each disturbance type was also gridded to a 1 km<sup>2</sup> resolution and represent total km<sup>2</sup>/km<sup>2</sup> for polygonal disturbances and km/km<sup>2</sup> for linear disturbances. In total, nineteen individual raster layers were produced including layers representing total polygonal and linear disturbances. The dataset was updated for some ranges in 2012 and 500m buffers were applied. More recently, the dataset was updated for all ranges in 2015 using 30-m and 15-m Landsat 8 imagery from 2015-2017.
  
  - Data years: 2010, 2015
  - References: Pasher et al. 2013
  - Website: http://open.canada.ca/data/en/dataset?q=Boreal+ecosystem+anthropogenic+disturbance

### Alberta Human Footprint

Alberta Human Footprint. From the ABMI website: "This comprehensive layer (updated every two years) includes human footprint information related to the energy, forestry, and agriculture industries, as well as urban development. The ABMI's human footprint information is core to understanding relationships between human land use, habitat, and species abundance. These data are used to support policy development, regional planning, and cumulative effects management decisions." The Human Footprint Index (HFI) has being developed every 2-3 years since 2007.

  - Data years: 2007, 2010, 2012, 2014, 2017
  - References: ABMI 2017
  - Website: https://www.abmi.ca/home/data-analytics/da-top/da-product-overview/Human-Footprint-Products.html

## Alaska Datasets

### NWBLCC Anthropogenic Footprint

The Northwest Boreal LCC Anthropogenic Footprint maps the human footprint (currently mining) across interior Alaska and northwestern Canada. The map provides a seamless dataset that spanned state, provincial and territorial boundaries to represent an initial look at intactness in the boreal ecosystems of western Canada and Alaska. Datasets representing past and present human footprint across the Northwest Boreal Landscape. Currently, only the mining footprint layer is available. It was created by digitizing visible mining footprints using best available digital imagery layers (primarily GeoNorth Ortho WMS layer and ESRI global imagery service) and represents a snapshot in time during the period between 2010-2016.

  - Data years: 2010-2016
  - References: Geist et al. 2017
  - View and download data: http://accs.uaa.alaska.edu/landscape-ecology/northwest-boreal-anthropogenic-footprint/
  - Online map: https://accsmaps.maps.arcgis.com/apps/Styler/index.html?appid=23f6711c8955419589d31cd5da582839
  - Website: http://accs.uaa.alaska.edu/landscape-ecology/northwest-boreal-anthropogenic-footprint/

### Alaska Landscape Condition

The landscape condition model was developed to measure the impact of the human footprint on a landscape. The LCM weighs the relative influence of different types of human activities to arrive at five condition classes ranging for very low (0.0-0.2) to very high (0.8-1.0) impact. The "very low" class combined with the Alaska IFL was then used to derive a landscape intactness dataset.

  - Data years: 2014
  - References: Trammell and Aisu 2016
  - Website: https://accscatalog.uaa.alaska.edu/dataset/landscape-condition-alaska

### Alaska Intact Forest Landscape

The Alaska Intact Forest Landscapes map depicts Alaska's remaining forest landscape fragments using three classes: 5,000-10,000 hectares, 10,000-50,000 hectares, and &gt;50,000 ha. The map was produced using (i) existing datasets describing major anthropogenic changes/disturbances (e.g., roads, other linear features, reservoirs) to exclude large areas influenced by human activities and (ii) satellite imagery (Landsat 5 and 7, 30m) to identify finer scale anthropogenic disturbances (e.g., cutblocks, cutlines) within candidate intact forest landscapes. Note that, similar to the Canada IFL dataset, fires were treated as natural disturbances.

  - Data years: 1985, 2001
  - References: Strittholt et al. 2006
  - Website: https://databasin.org/search/#query=Alaska%20intact%20forest%20landscapes

---

# Individual Disturbances

Several disturbance datasets have been developed recently, some of which have been used to update both the Canada and Global IFL datasets. The datasets represent changes in forest cover with or without attribution to disturbance type.

## Global Datasets

### Global Forest Change

Global maps of forest cover change (Hansen et al. 2013). The maps were developed using Landsat imagery at a resolution of 30m and covers latitudes 80N and 60S. Four metrics are used: (i) percent tree cover in 2000, (ii) cover loss 2000-2018, (iii) cover gain 2000-2018, and (iv) year of cover loss. There is no attribution of disturbance type. The datasets was recently updated to 2018.
  
  - Data years: 2000-2018
  - References: Hansen et al. 2013
  - Website: https://earthenginepartners.appspot.com/science-2013-global-forest

---

## Canada Datasets

### Annual Mapping of Large Forest Disturbances

Annual mapping of large forest disturbances in Canada (Guindon et al. 2014). Annual mapping of large forest disturbances across Canada's forests using 250m MODIS imagery from 2000 to 2011. At total of 22 raster maps were generated representing fractional change and disturbance type. Fractional change is mapped as a continuous variable at the pixel level. Disturbance types were classified as no-change, fire, harvesting, or flooding.
  
  - Data years: 2000-2011
  - References: Guindon et al. 2014
  - Website: http://www.nrcresearchpress.com/doi/abs/10.1139/cjfr-2014-0229#.Wcu9msiGPRZ (See Supplementary data)

### Canada Landsat Disturbance

Canada Landsat Disturbance (CanLaD) 2017. This dataset includes a set of raster maps in which areas affected by fire or by harvest from 1984 to 2015 are identified at the level of individual 30m pixels on the Landsat grid. Details of the product development can be found in Guindon et. al. (2017, 2018).

  - Data years: 1984-2015
  - References: Guindon et al. 2017, 2018
  - Website: https://open.canada.ca/data/en/dataset/add1346b-f632-4eb9-a83d-a662b38655ad

### Satellite forest monitoring

Satellite forest monitoring in Canada. Online satellite-derived forest change map for Canada with information on the amount, type, and rates of disturbances from 1985-2011. The maps were developed using Landsat imagery at a resolution of 30m and estimate change type as being fire, infrastructure, harvest, or untyped.
  
  - Data years: 1985-2011
  - References: White et al. 2017
  - Website: http://forests.foundryspatial.com/

---

# Regionalizations

## Global Datasets

### Anthropogenic Biomes

Anthropogenic Biomes. From The Encyclopedia of Earth: "Anthropogenic biomes describe globally-significant ecological patterns within the terrestrial biosphere caused by sustained direct human interaction with ecosystems, including agriculture, urbanization, forestry and other land uses. Conventional biomes, such as tropical rainforests or grasslands, are based on global vegetation patterns related to climate. Now that humans have fundamentally altered global patterns of ecosystem form, process, and biodiversity, anthropogenic biomes provide a contemporary view of the terrestrial biosphere in its human-altered form. Anthropogenic biomes may also be termed "anthromes" to distinguish them from conventional biome systems, or "human biomes" (a simpler but less precise term)". The three wildland categories (wild forest, sparse trees, and barren) are of primary interest.

  - Data years: 2010
  - References: Ellis and Ramankutty 2010
  - Website: http://www.ecotope.org/anthromes/v2/data/


### World terrestrial ecosystems

From Sayre et al. (2020): "We describe a new set of maps of globally consistent climate regions and ecosystems at a much finer spatial resolution (250m) than existing ecological regionalizations. The new map of terrestrial World Ecosystems was derived from the objective development and integration of 1) global temperature domains, 2) global moisture domains, 3) global landforms, and 4) 2015 global vegetation and land use. These new terrestrial World Ecosystems do not include either freshwater or marine ecosystems, but analog products for the freshwater and marine domains are in development. A total of 431 World Ecosystems were identified, and of these a total of 278 units were natural or semi-natural vegetation/environment combinations, including different kinds of forestlands, shrublands, grasslands, bare areas, and ice/snow regions. The remaining classes were different kinds of croplands and settlements." The dataset can be downloaded from the bottom of the storymap page.

  - Data years: 2020
  - References: Sayre et al. 2020
  - Storymap: https://storymaps.arcgis.com/stories/a4a6b1f779be4b64816d1876cfe669b9

### DHI Clusters


The DHIs are designed for biodiversity assessments and to describe habitats of different species. Three individual indices comprise the DHIs:

  - DHI cum - cumulative DHI, i.e., the area under the phenological curve of a year
  - DHI min - minimum DHI, i.e., the minimum value of the phenological curve of a year
  - DHI var - seasonality DHI, i.e., the coefficient of variation of the phenological curve of a year

The python code (wrappers for GDAL and GRASS) to create DHI data is available from the bottom of the website.

  - Data years:
  - References: Coops et al. 2019
  - Website: http://silvis.forest.wisc.edu/data/dhis-clusters/


# Climate

## Canada Datasets

### Climate moisture index

Climate moisture index (CMI) is a measure of the water deficit (or surplus) in soil, calculated as the yearly average precipitation minus yearly potential evapotranspiration expressed in units of cm of water per year (Hogg 1997). We used data from Hamann et al. 2013 with resolutions of 1-km2 for western North America and 4-km2 for North America, resampling the latter to 1-km2.

## Productivity

## Global Datasets

### Gross primary productivity

Gross primary productivity (GPP) is an indicator of the amount of carbon absorbed by photosynthesis, measured in kg per meter squared per year (C kg/m2/yr). It is calculated as an average of 15 years of data (2000-2014) from the MODIS satellite and has a resolution of 1 km2 (Zhao and Running 2010); 

### Dynamic habitat indices

The DHIs are designed for biodiversity assessments and to describe habitats of different species. Three individual indices comprise the DHIs:

  - DHI cum - cumulative DHI, i.e., the area under the phenological curve of a year
  - DHI min - minimum DHI, i.e., the minimum value of the phenological curve of a year
  - DHI var - seasonality DHI, i.e., the coefficient of variation of the phenological curve of a year

The python code (wrappers for GDAL and GRASS) to create DHI data is available from the bottom of the website.

  - Data years: annually for 2003-2015; composite for 2003-2014
  - References: Hobi et al. 2017, Radelof et al. 2019
  - Website: http://silvis.forest.wisc.edu/data/dhis/
  - Website: http://silvis.forest.wisc.edu/data/dhis-clusters/

# Hydrology

## Canada Datasets

### Lake edge density

Lake edge density (LED) is an indicator of the density of riparian habitat, measured in km/km2 within 100 km2 circular units (BEACONs 2011). This dataset was created using the 1:1,000,000 lakes and wide rivers coverage from the Atlas of Canada?s National Scale Frameworks Hydrology (v6.0, NRCAN 2009);


# Land cover

## North America Datasets

### NALCC 2010

Land cover (LCC) is a categorical descriptor of vegetation on the landscape and was measured using the 2010 Land Cover of North America based on 250m MODIS satellite imagery, containing 19 cover types (CEC 2013). We removed landcover classes associated with anthropogenic disturbances (urban, agriculture).

# Species

## Canada Datasets

### Songbird density

### Waterfowl density

# Topography

## Digital Elevation Data

The Canadian Digital Elevation Data is produced by Natural Resources Canada. The CDED data set consists of 30 metre (1:50000) and 90 metre (1:250 000) resolution digital elevation models (DEM) of Canada. Data is available in DEM format which is supported by a variety of software including: ArcView 3.x, ArcGIS, MapInfo, IDRISI, and PCI to name a few. These files are derived from the 1:50 000 and 1:250 000 NTDB map sheets.

  - Website: www.geobase.ca

# References

Bryant, D., Nielsen, D., Tangley, L. 1997. The last frontier forests: Ecosystems and economies on the edge. World Resources Institute, Washington, D.C.

Coops, N.C., Kearney, S.P., Bolton, D.K. et al. Remotely-sensed productivity clusters capture global biodiversity patterns. Sci Rep 8, 16261 (2018). https://doi.org/10.1038/s41598-018-34162-8

Ellis, E.C., and Ramankutty, N., 2008. Putting people in the map: anthropogenic biomes of the world. Frontiers in Ecology and the Environment 6, <doi:10.1890/070062>. URL: <http://www.esajournals.org/doi/abs/10.1890/070062>

Ellis, E. C., K. Klein Goldewijk, S. Siebert, D. Lightman, and N. Ramankutty. 2010. Anthropogenic transformation of the biomes, 1700 to 2000. Global Ecology and Biogeography 19(5):589-606

Erb, K.-H., Gaube, V., Krausmann, F., Plutzar, C., Bondeau, A., Haberl, H. 2007. A comprehensive global 5min resolution land-use dataset for the year 2000 consistent with national census data. Journal of Land Use Science 2(3): 191-224. URL: <http://www.informaworld.com/smpp/content~content=a783007657~db=all~order=page>

Geist, M., Aisu, M., Lema, P., Trammell, E.J. 2017. Spatial estimates of surface mining footprints in northwest boreal ecoregions of Alaska and Canada.

Grantham et al. 2020 Anthropogenic modification of forests means only 40% of remaining forests have high ecosystem integrity. Nature Communications 11: 5978. https://doi.org/10.1038/s41467-020-19493-3

Guindon, L, Bernier, PY, Beaudion, A, Pouliot, D, Villmaire, P, Hall, RJ, Latifovic, R, St-Amant, R. 2014. Annual mapping of large forest disturbances across Canada's forests using 250m MODIS imagery from 2000 to 2011. Canadian Journal of Forest Research 44(12): 1545-1554.

Guindon, L, Villemaire, P, St-Amant, R, Bernier, PY, Beaudoin, A, Caron, F, Bonucelli, M, Dorion, H. 2017. Canada Landsat Disturbance (CanLaD): a Canada-wide Landsat-based 30-m resolution product of fire and harvest detection and attribution since 1984.

Guindon, L, Bernier, P.Y., Gauthier, S, Stinson, G, Villemaire, Beaudoin, A. 2018. Missing forest cover gains in boreal forests explained. Ecosphere 9(1):e02094. 10.1002/ecs2.2094

Haberl, H., Erb, K.H., Krausmann, F., Gaube, V. Bondeau, A., Plutzar, C., Gingrich, S., Lucht, W., Fischer-Kowalski, M. 2007. Quantifying and mapping the human appropriation of net primary production in earth's ecosystems. PNAS (104): 12942-12947. URL: <http://www.pnas.org/content/104/31/12942.full>

Hansen, MC, Potapov, PV, Moore, R, Hancher, M, Turubanova, SA, Tyukavina, A, Stenham, SV, Goetz, SJ, Loveland, TR, Kommareddy, A, Egarov, A, Chini, L, Justice, CO, Townshend, JRG. 2013. High- resolution global maps of 21st-century forest cover change. Science 342: 850-853.

Hermosilla, T, Wulder, MA, White, JC, Coops, NC, Hobart, GW. 2015. Regional detection, characterization, and attribution of annual forest change from 1984 to 2012 using Landsat-derived time-series metrics. Remote Sensing of Environment 170: 121-132.

Hermosilla, T, Wulder, MA, White, JC, Coops, NC, Hobart, GW, Campbell, LB. 2016. Mass data processing of time series Landsat imagery: pixels to data products for forest monitoring. International Journal of Digital Earth 9: 1035-1054.

Hobi, M.L., Dubinin, M., Graham, C.H., Coops, N.C., Clayton, M.K., Pidgeon, A.M., & Radeloff, V.C. 2017. A comparison of Dynamic Habitat Indices derived from different MODIS products as predictors of avian species richness. Remote Sensing of Environment, 195, 142-152.

Imhoff, M. L., Bounoua, L., Ricketts, T., Loucks, C., Harriss, R., Lawrence, W. T. 2004. Global patterns in human consumption of net primary production. Nature 429, 870-873. URL: <http://sedac.ciesin.columbia.edu/es/hanpp.html>

Jacobson, A.P., Riggio, J., Tait, A.M. and Baillie, J.E. 2019. Global areas of low human impact (Low Impact Areas) and fragmentation of the natural world. Scientific reports 9(1):1-13. http://dx.doi.org/10.1038/s41598-019-50558-6

Kennedy C.M., Oakleaf J.R., Theobald D.M., Baruch-Mordo S., Kiesecker J. 2019. Managing the middle: A shift in conservation priorities based on the global human modification gradient. Global Change Biology 25:811-826. https://doi.org/10.1111/gcb.14549

Lee, P., Gysbers, J.D., Stonojevic, Z. 2006. Canada's forest landscape fragments: A first approximation (A Global Forest Watch Canada Report). Edmonton, Alberta: Global Forest Watch Canada. 97pp.

Lee, P. G. 2009. Caution against using intact forest-landscapes data at regional scales. Ecology and Society 14(1): r1. URL: <http://www.ecologyandsociety.org/vol14/iss1/resp1/>

Lee, P.G. and Cheng, R. 2014. Human Access in Canada's Landscape. Global Forest Watch Canada.

Pasher, J, Seed, E, Duffe, J. 2013. Development of boreal ecosystem anthropogenic disturbance layers for Canada based on 2008 to 2010 Landsat imagery. Can. J. Remote Sensing 39(1): 42-58.

Potapov, P., Yaroshenko, A., Turubanova, S., Dubinin, M., Laestadius, L., Thies, C., Aksenov, D., Egorov, E., Yesipova, Y., Glushkov, I., Karpachevskiy, M., Kostikova, A., Manisha, A., Tsybikova, E., Zhuravleva, I.. 2008. Mapping the world's intact forest landscapes by remote sensing. Ecology and Society 13(2): 51. URL: <http://www.ecologyandsociety.org/vol13/iss2/art51/>

Potapov, P., Hansen, M.C., Laestadius, L., Turubanova, S., Yaroshenko, A., Thies, C., Smith, W., Zhuravleva, I., Komarova, A., Minnemeyer, S., Esipova, E. 2017 The last frontiers of wilderness: Tracking loss of intact forest landscapes from 2000 to 2013. Science Advances 3: 1-13.

Radeloff, V. C., M. Dubinin, N. C. Coops, A. Allen, T. M. Brooks, M. Clayton, G. Costa, C. H. Graham, D. Helmers, A. R. Ives, D. Kolesov, A. M. Pidgeon, G. Rapacciuolo, E. Razenkova, N. Suttidate, B. E. Young, L. Zhu, and M. Hobi. 2019. The Dynamic Habitat Indices (DHIs) from MODIS and global biodiversity. Remote Sensing of Environment, 222: 204-214

Sanderson, E.W., Jaiteh, M., Levy, M.A., Redford, K.H., Wannebo, A.V., Woolmer, G. 2002. The human footprint and the last of the wild. BioScience 52:891-904.

Sayre et al. 2020. An assessment of the representation of ecosystems in global protected areas using new maps of World Climate Regions and World Ecosystems. Global Ecology and Conservation 21. https://doi.org/10.1016/j.gecco.2019.e00860

Smith, W. and Cheng, R. 2016. Canada's Intact Forest Landscapes Updated to 2013. Ottawa: Global Forest Watch Canada. 26 pp.

Strittholt, J.R., Nogueron, R., Alvarez, M., and Bergquist, J. 2006. Mapping undisturbed landscapes in Alaska: An overview report. Conservation Biology Institute and World Resource Institute. URL: <https://www.wri.org/publication/mapping-undisturbed-landscapes-alaska> (accessed April 01, 2020).

UNEP. 2001. Nelleman, C., Kullerud, L., Vistnes, I., Forbes, B.C., Husby, E., Kofinas, G.P., Kaltenborn, B.P., Rouaud, J., Magomedova, M., Bobiwash, R., Lambrechts, C., Schei, P.J., Tveitdal, S., Gron, O., Larsen, T.S. GLOBIO. Global methodology for mapping human impacts on the biosphere. UNEP/DEWA/TR.01-3.

Venter, O. et al. 2016a Global terrestrial Human Footprint maps for 1993 and 2009. Sci. Data 3, 160067.

Venter, O. et al. 2016b. Sixteen years of change in the global terrestrial human footprint and implications for biodiversity conservation. Nat. Commun. 7, 12558

White, JC, Wulder, MA, Hermosilla, T, Coops, NC, Hobart, GW 2017 A nationwide annual characterization of 25 years of forest disturbance and recovery for Canada using Landsat time series. Remote Sensing of Environment 194: 303-321.
