---
title: "PostGIS"
date: "January 3, 2019"
author: "Pierre Vernier"
output:
  html_document:
    toc: TRUE
    toc_float: true
    keep_md: no
---

Installing PostgreSQL/PostGIS and Anaconda on Windows.

# Installing tools

In this section, I will describe how I installed PostgreSQL/PostGIS and Python (Anaconda) on a 64-bit Windows 10 machine. If you know of a simpler or more robust method, please let me know (pierre.vernier@gmail.com). Even though I describe the process as steps, there are no requirements to install these in this particular order.

## Step 1 - Install PostgreSQL

You can download the latest version from here:

  * https://www.enterprisedb.com/downloads/postgres-postgresql-downloads

In my case I selected the latest version (11.0) for Windows 10 64-bit (Windows x86-64). Once downloaded, start the installation by double-clicking on the file. I selected all the default parameters and used "postgres" as the password for the "postgres" database that is created during the installation process. Towards the end of the installation, you can select extensions - namely the latest version of PostGIS. That's all there is to it!

## Step 2 - Install Anaconda

Anaconda includes Python and various libraries that are useful for spatial data management and analysis e.g., GDAL/OGR. Specifically, the ogr2ogr utility includes most of the drivers needed to import vector datasets (e.g., shapefiles, file geodatabases) into PostGIS. You can download the latest version from here:

  * https://www.anaconda.com/download/
  
I downloaded the Python 3.7 64-Bit Graphical Installer. Once downloaded, start the installation and select the default prompts. At this point, you should be able to start the Anaconda prompt. From there, you can run various utilities, Python scripts, and install additional libraries as needed (i.e., conda install ...).


# Viewing PostGIS maps

It is often useful to have a look at intermediate results when running queries or conducting an analysis. There are no easy ways to do this within PostGIS, however I've come across a few approaches that are relatively simple.

## pgAdmin 4

With recent versions of PostGIS, it is now possible to view the geometry of a spatial table if it is in a geographic projectiong (epgs = 4326).

## QGIS

## R



## Python

