<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Habitat suitability – Finlayson Caribou and the KZK Mine Project</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./movement.html" rel="next">
<link href="./habitat.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./hsi.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Habitat suitability</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Finlayson Caribou and the KZK Mine Project</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./yesab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">YESAB Report 2020</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kzk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Kudz Ze Kayah</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./population.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Population Estimates</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ranges.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Seasonal Ranges</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./habitat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Habitat requirements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hsi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Habitat suitability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./movement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Seasonal movements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Literature cited</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">8</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#study-area" id="toc-study-area" class="nav-link" data-scroll-target="#study-area"><span class="header-section-number">8.1</span> Study Area</a></li>
  <li><a href="#habitat-selection" id="toc-habitat-selection" class="nav-link" data-scroll-target="#habitat-selection"><span class="header-section-number">8.2</span> Habitat Selection</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">9</span> Methods</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">9.1</span> Data Sources</a></li>
  <li><a href="#variables-and-fuzzy-membership-functions" id="toc-variables-and-fuzzy-membership-functions" class="nav-link" data-scroll-target="#variables-and-fuzzy-membership-functions"><span class="header-section-number">9.2</span> Variables and Fuzzy Membership Functions</a>
  <ul class="collapse">
  <li><a href="#elevation" id="toc-elevation" class="nav-link" data-scroll-target="#elevation"><span class="header-section-number">9.2.1</span> Elevation</a></li>
  <li><a href="#slope" id="toc-slope" class="nav-link" data-scroll-target="#slope"><span class="header-section-number">9.2.2</span> Slope</a></li>
  <li><a href="#aspect-rut-and-post-calving-only" id="toc-aspect-rut-and-post-calving-only" class="nav-link" data-scroll-target="#aspect-rut-and-post-calving-only"><span class="header-section-number">9.2.3</span> Aspect (rut and post-calving only)</a></li>
  <li><a href="#vegetation-cover" id="toc-vegetation-cover" class="nav-link" data-scroll-target="#vegetation-cover"><span class="header-section-number">9.2.4</span> Vegetation Cover</a></li>
  <li><a href="#winter-precipitation-late-winter-only" id="toc-winter-precipitation-late-winter-only" class="nav-link" data-scroll-target="#winter-precipitation-late-winter-only"><span class="header-section-number">9.2.5</span> Winter Precipitation (late winter only)</a></li>
  </ul></li>
  <li><a href="#model-development" id="toc-model-development" class="nav-link" data-scroll-target="#model-development"><span class="header-section-number">9.3</span> Model Development</a></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation"><span class="header-section-number">9.4</span> Model Evaluation</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">10</span> Results</a>
  <ul class="collapse">
  <li><a href="#rut-and-post-calving-habitat-suitability" id="toc-rut-and-post-calving-habitat-suitability" class="nav-link" data-scroll-target="#rut-and-post-calving-habitat-suitability"><span class="header-section-number">10.1</span> Rut and Post-Calving Habitat Suitability</a></li>
  <li><a href="#late-winter-habitat-suitability" id="toc-late-winter-habitat-suitability" class="nav-link" data-scroll-target="#late-winter-habitat-suitability"><span class="header-section-number">10.2</span> Late Winter Habitat Suitability</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">11</span> Discussion</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">12</span> Limitations</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">13</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Habitat suitability</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Introduction</h1>
<p>The Kudz Ze Kayah (KZK) Project is a proposed base-metal mine in the Yukon Plateau-North Ecoregion of the Canadian Boreal Cordillera Ecozone, approximately 260 km northwest of Watson Lake and 115 km southeast of Ross River, Yukon. The Project lies within the traditional home range of the <strong>Finlayson caribou herd (FCH)</strong>, a population of Northern Mountain caribou (<em>Rangifer tarandus caribou</em>) assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC) as a <strong>Species of Special Concern</strong>, and listed as such under the federal <em>Species at Risk Act</em> (SARA) in 2005. The FCH is of significant ecological, economic, and cultural importance to the Kaska First Nation, resident and guided hunters, and the general public.</p>
<p>The federal <em>Management Plan for the Northern Mountain Population of Woodland Caribou</em> directs responsible agencies to (i) identify and assess the quality, quantity, and distribution of important caribou habitats, and (ii) manage and conserve those habitats. To meet these objectives at the KZK Project site, Alexco Environmental Group Inc.&nbsp;(AEG) developed a series of <strong>habitat suitability index (HSI) models</strong> for the FCH, built from over three decades of Yukon Government survey data supplemented by project-specific surveys carried out by AEG between 2015 and 2017.</p>
<p>Three life-requisite seasons were modelled:</p>
<ul>
<li><strong>Post-calving</strong> (summer dispersal/growth period) and <strong>rut</strong> (fall breeding aggregation) — modelled in the December 2016 <em>Caribou Habitat Suitability Report</em> submitted as Appendix E-8 of the Project Proposal.</li>
<li><strong>Late winter</strong> — modelled in a January 2018 supplementary report (<em>Caribou Late Winter Habitat Suitability Report</em>), prepared after the Yukon Environmental and Socio-economic Assessment Board (YESAB) informally requested a winter-season model during its Adequacy Review; this model was subsequently appended to BMC’s Response Report #6 to YESAB Information Request (IR6), submitted July 2020. Winter habitat overlaps the Project’s Access Road but not the mine site itself, so it was not part of the original scope.</li>
</ul>
<p>The purpose of each HSI was to predict the spatial distribution of suitable caribou habitat within the <strong>Local Study Area (LSA)</strong> — a 3 km buffer around proposed mine infrastructure and a 1.5 km buffer around the Tote/Access Road — and across the FCH’s traditional home range (~23,000 km²), in order to support the design of avoidance and mitigation measures and to assess potential residual effects of the Project on caribou habitat.</p>
<p>This workbook consolidates the background, methods, and results reported across these documents and reproduces the key summary statistics, membership functions, and results tables using R.</p>
<section id="study-area" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="study-area"><span class="header-section-number">8.1</span> Study Area</h2>
<p>The Project sits in the Geona Creek valley in the northeastern foothills of the Pelly Mountains, straddling the subalpine and lower alpine zones. Treeline occurs at approximately 1,550 m above sea level (masl); above 1,700 masl the landscape transitions to alpine tundra dominated by dwarf shrub, graminoid, and lichen cover. The Tote Road/Access Road corridor parallels the lower reaches of Finlayson Creek through open white and black spruce forest.</p>
<p>The FCH is an elevational, migratory ecotype. In spring, roughly two-thirds of the herd move from wintering grounds near the Pelly River to calve in the highlands of the southeastern Pelly Mountains; the remainder travel to mountains northeast of Finlayson Lake. Through summer, caribou disperse onto alpine plateaus and ridges to avoid predators and to seek relief from insects and heat, aggregating again in open alpine/subalpine habitat for the fall rut (peaking mid-October). In late fall the herd migrates northwest back toward the Pelly lowlands, becoming increasingly reliant on terrestrial lichen (roughly 70% of the winter diet) as green forage senesces. In late winter, the FCH concentrates in the low-elevation forest and shrublands around the Pelly River and Finlayson Lake, an area that sits in an <strong>orographic rain/snow-shadow</strong> north of the Pelly Mountains and typically receives less than 30 cm of precipitation annually — far below snow depths (50–90 cm) known to impede caribou mobility.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 2.1 – Study area extents</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Study Area</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Extent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Post-calving study area</td>
<td style="text-align: left;">2,036,919 ha</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rut study area</td>
<td style="text-align: left;">2,037,259 ha</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FCH traditional home range</td>
<td style="text-align: left;">~2,300,000 ha (23,000 km²)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Local Study Area (LSA)</td>
<td style="text-align: left;">3 km buffer around mine infrastructure; 1.5 km buffer around Tote/Access Road</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="habitat-selection" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="habitat-selection"><span class="header-section-number">8.2</span> Habitat Selection</h2>
<p>Caribou habitat requirements vary strongly by season, which is the ecological basis for building season-specific HSI models rather than a single year-round model:</p>
<ul>
<li><strong>Spring/calving (Apr–Jun):</strong> migration to calving grounds; solitary, high-visibility alpine sites or concealing subalpine cover, away from alternate prey (e.g., moose) that support predator populations.</li>
<li><strong>Summer/post-calving (Jun–Sep):</strong> dispersal into small groups on upper subalpine/alpine ridges, plateaus and upper-elevation streams; forage on forbs, deciduous leaves, lichens, fungi, grasses, and sedges; use of windy ridges and snow patches for insect and heat relief.</li>
<li><strong>Fall/rut (peaks mid-October):</strong> aggregation in open alpine and subalpine habitat; 2015–2016 early winter surveys found FCH remaining on rutting grounds in the Project area until mid-December.</li>
<li><strong>Migration (late fall/spring):</strong> transit through boreal forest, subalpine, shrubland, and alpine tundra; diet shifts toward terrestrial lichen as herbaceous forage dies off.</li>
<li><strong>Late winter:</strong> concentration in low-elevation, low-snowpack forest/shrubland in the Pelly River–Finlayson Lake snow-shadow, where shallow snow allows cratering to access terrestrial lichen.</li>
</ul>
<p>Winter habitat suitability was not modelled in the original 2016 report because the traditional core winter range lies ~100 km northwest of the Project site, outside the Project’s zone of influence (ZOI); the model was added later at YESAB’s request because the herd’s late-winter range overlaps the Access Road corridor.</p>
</section>
</section>
<section id="methods" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Methods</h1>
<section id="data-sources" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">9.1</span> Data Sources</h2>
<p>Each HSI combined spatial environmental layers with independently collected caribou location data used for <strong>calibration</strong> (satellite collar and VHF telemetry relocation data — higher positional accuracy, lower sample size) and <strong>evaluation</strong> (aerial survey data — lower positional accuracy but far larger sample size). This split allowed an independent cross-validation approach (calibrate on one dataset, evaluate on another) rather than testing the model against the same data used to build it.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 4.1 – Habitat Suitability Index data sources</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Dataset</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Used in</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Digital Elevation Model (DEM)</td>
<td style="text-align: left;">Elevation raster, resampled to 25 m</td>
<td style="text-align: left;">Rut / Post-calving / Late winter</td>
</tr>
<tr class="even">
<td style="text-align: left;">Slope</td>
<td style="text-align: left;">Degrees of slope derived from DEM (25 m)</td>
<td style="text-align: left;">Rut / Post-calving / Late winter</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aspect</td>
<td style="text-align: left;">Degrees of aspect derived from DEM (25 m)</td>
<td style="text-align: left;">Rut / Post-calving only</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vegetation cover</td>
<td style="text-align: left;">Dominant class from Predictive Ecosystem Map (PEM), 25 m</td>
<td style="text-align: left;">Rut / Post-calving / Late winter</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Winter precipitation</td>
<td style="text-align: left;">1961–1990 climate normal, 1,672 m resampled to 25 m (PRISM/SNAP)</td>
<td style="text-align: left;">Late winter only</td>
</tr>
<tr class="even">
<td style="text-align: left;">Caribou satellite collar points</td>
<td style="text-align: left;">FCH satellite locations, 2004–2011 (3 individuals)</td>
<td style="text-align: left;">Calibration</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Caribou VHF relocation collar points</td>
<td style="text-align: left;">Fixed-wing telemetry relocations, 1982–1987, 2004</td>
<td style="text-align: left;">Calibration</td>
</tr>
<tr class="even">
<td style="text-align: left;">Caribou aerial survey points (YG)</td>
<td style="text-align: left;">Helicopter/fixed-wing survey locations, 1982–2014/2017</td>
<td style="text-align: left;">Evaluation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Caribou aerial survey points (AEG/EDI)</td>
<td style="text-align: left;">Project-acquired survey locations, 2015–2017</td>
<td style="text-align: left;">Evaluation</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 4.2 – Caribou location observations used per season</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Survey methodology</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Rut</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Post-calving</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Late winter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Satellite collar</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">14 (3 from FCH)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Telemetry/VHF relocation</td>
<td style="text-align: left;">104</td>
<td style="text-align: left;">51</td>
<td style="text-align: left;">136</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aerial survey</td>
<td style="text-align: left;">2,129</td>
<td style="text-align: left;">577</td>
<td style="text-align: left;">1,827</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: left;">2,248</td>
<td style="text-align: left;">645</td>
<td style="text-align: left;">1,977</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Known biases affecting each survey type: satellite-collared animals were originally deployed to track the adjacent Nahanni herd, so only 3 FCH individuals were represented and their locations were sometimes biased toward the Nahanni range to the east; VHF relocation data have ~200 m positional accuracy because animals were located from a fixed-wing aircraft; and aerial survey flights deliberately targeted areas of expected high caribou density for demographic counts, over-representing those areas in the evaluation dataset.</p>
</section>
<section id="variables-and-fuzzy-membership-functions" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="variables-and-fuzzy-membership-functions"><span class="header-section-number">9.2</span> Variables and Fuzzy Membership Functions</h2>
<p>Four environmental variables were evaluated for the rut and post-calving models — <strong>elevation, slope, aspect, and vegetation cover</strong> — chosen because they are ecologically meaningful, well supported in the literature, and available continuously across the entire FCH home range. The late-winter model substituted <strong>winter precipitation</strong> for aspect (aspect showed no distributional signal in low-relief winter range and was dropped).</p>
<p>Elevation, slope, and precipitation were treated as <strong>continuous variables</strong> and rescaled to a 0–1 suitability index using a <strong>linear fuzzy membership function</strong>, with breakpoints set from the frequency distribution of calibration-data locations along each variable. Aspect and vegetation cover are <strong>discrete/categorical variables</strong>, ranked 0–1 directly from observation frequency in each class and refined with expert opinion.</p>
<section id="elevation" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="elevation"><span class="header-section-number">9.2.1</span> Elevation</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsi_files/figure-html/elevation-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fuzzy membership functions for elevation suitability, by season</figcaption>
</figure>
</div>
</div>
</div>
<p>Post-calving suitability peaks at higher elevation (1,600–1,900 masl) than rut (1,500–1,800 masl), consistent with caribou seeking high ridges/plateaus for predator, heat, and insect avoidance during summer. Late-winter suitability is highest at low elevation (≤1,000 masl) and declines to zero by 1,500 masl, reflecting the herd’s descent into the Pelly River/Finlayson Lake lowlands.</p>
</section>
<section id="slope" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="slope"><span class="header-section-number">9.2.2</span> Slope</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsi_files/figure-html/slope-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fuzzy membership functions for slope suitability, by season</figcaption>
</figure>
</div>
</div>
</div>
<p>Rut habitat is most suitable on gentle terrain (≤25°), falling to zero by 60°. Post-calving habitat tolerates a wider plateau of moderate slope (10°–50°), consistent with use of ridges and upper plateaus. Late-winter habitat is essentially flat-terrain habitat, with suitability collapsing above ~12.5°, reflecting use of the lowland forest/shrub mosaic rather than mountain terrain.</p>
</section>
<section id="aspect-rut-and-post-calving-only" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="aspect-rut-and-post-calving-only"><span class="header-section-number">9.2.3</span> Aspect (rut and post-calving only)</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 4.4 – Aspect suitability class rankings</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Aspect class (degrees)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rut suitability</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Post-calving suitability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">≤0</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">0–90</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">90–180</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">180–270</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">270–360</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Aspect showed the weakest discriminating signal of any variable in the rut/post-calving models (observation frequency varied only modestly across the four quadrants) and consequently received a lower variable weighting than elevation, slope, or vegetation. It was dropped altogether from the late-winter model because winter range is largely flat terrain, where aspect has little ecological meaning.</p>
</section>
<section id="vegetation-cover" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="vegetation-cover"><span class="header-section-number">9.2.4</span> Vegetation Cover</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 4.5 – Vegetation cover suitability class rankings</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Vegetation class</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rut</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Post-calving</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Late winter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Herb/Bryoid</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shrub</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deciduous</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mixedwood</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coniferous</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treed wetland</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Water/Ice</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rock</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Vegetation classes were derived from the <em>Regional Ecosystems of East-Central Yukon Predictive Ecosystem Map</em> (PEM; Makonis Consulting Ltd.&nbsp;2013), reclassified to dominant cover type. Herb/bryoid and shrub classes dominate suitable rut and post-calving habitat, while coniferous and shrub cover — the principal terrestrial-lichen-bearing habitat — dominate suitable late-winter habitat.</p>
</section>
<section id="winter-precipitation-late-winter-only" class="level3" data-number="9.2.5">
<h3 data-number="9.2.5" class="anchored" data-anchor-id="winter-precipitation-late-winter-only"><span class="header-section-number">9.2.5</span> Winter Precipitation (late winter only)</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsi_files/figure-html/precip-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Fuzzy membership function for winter precipitation suitability</figcaption>
</figure>
</div>
</div>
</div>
<p>Winter precipitation (a proxy for snow depth) was added specifically for the late-winter model, since shallow snowpack is critical to caribou cratering access to terrestrial lichen. Suitability is highest below 70 mm and falls to zero by 85 mm, consistent with the FCH winter range’s position in the Pelly Mountains’ rain/snow-shadow (long-term average snowpack along the Robert Campbell Highway ≈ 40 cm, well below the 50–90 cm reported to impede caribou mobility).</p>
</section>
</section>
<section id="model-development" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="model-development"><span class="header-section-number">9.3</span> Model Development</h2>
<p>For each season, the reclassified variable layers (each rescaled 0–1) were resampled to a common 25 m grid, multiplied by an importance weight, and summed to produce a single continuous suitability surface (0–1). Aspect and vegetation (categorical, less discriminating) generally received lower weights than elevation and slope; for the late-winter model, all four variables were weighted evenly:</p>
<p><span class="math display">\[\text{Late winter HSI} = 0.25 \times \text{Elevation} + 0.25 \times \text{Slope} + 0.25 \times \text{Vegetation} + 0.25 \times \text{Precipitation}\]</span></p>
<p>Focal statistics (a 100 m / 4-cell radius smoothing window) were then applied to remove isolated single-cell artifacts and produce a spatially continuous surface, and the result was reclassified into <strong>six ordinal habitat classes</strong> (Nil, Very Low, Low, Moderate, Moderately High, High) following the British Columbia Wildlife Habitat Rating Standards (RIC 1999).</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Post-calving and Rut</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Winter</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div id="fig-hsi-workflow" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hsi-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig4-1_hsi_workflow_appendixE8.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hsi-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Figure 4-1 013 Habitat Suitability Index process workflow (BMC_APPENDIX_E-8_(Part_16)_WILDLIFE_BASELINE_REPORT_caribou habitat suitability, December 2016).
</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div id="fig-hsi-workflow" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hsi-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig4-1_hsi_process_workflow.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hsi-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Figure 4-1 013 Habitat Suitability Index process workflow (BMC KZK Response Report IR6, January 2018).
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="model-evaluation" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="model-evaluation"><span class="header-section-number">9.4</span> Model Evaluation</h2>
<p>Models were evaluated using the <strong>non-parametric Kendall tau test</strong>, chosen over Spearman’s rank correlation because it is less sensitive to error and performs better with smaller sample sizes. The test assessed whether the six ordinal HSI classes were correlated with the density of <em>independent</em> aerial survey observations (i.e., data withheld from model calibration). A model was accepted as statistically significant at α = 0.05, and where multiple candidate weighting/breakpoint schemes were tested, the version with the highest tau coefficient (strongest correlation) was retained as final. All statistics were computed in R (R Core Team 2014).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 4.6 – Model evaluation statistics (Kendall's tau, six-class ranking vs. aerial survey density)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Season</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kendall's tau</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Post-calving</td>
<td style="text-align: right;">1.0000</td>
<td style="text-align: right;">0.0014</td>
<td style="text-align: left;">Significant, very strong positive correlation</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rut</td>
<td style="text-align: right;">0.7333</td>
<td style="text-align: right;">0.0278</td>
<td style="text-align: left;">Significant, strong positive correlation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Late winter</td>
<td style="text-align: right;">1.0000</td>
<td style="text-align: right;">0.0014</td>
<td style="text-align: left;">Significant, very strong positive correlation</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsi_files/figure-html/evaluation-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Model evaluation strength by season</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="results" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Results</h1>
<section id="rut-and-post-calving-habitat-suitability" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="rut-and-post-calving-habitat-suitability"><span class="header-section-number">10.1</span> Rut and Post-Calving Habitat Suitability</h2>
<div id="fig-rut-hsi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rut-hsi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig5-1_rut_habitat_suitability.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rut-hsi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: Figure 5-1 – Finlayson Caribou Herd rut habitat suitability, home range and study area (BMC Appendix E-8, Part 17, November 2016).
</figcaption>
</figure>
</div>
<div id="fig-postcalving-hsi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-postcalving-hsi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig5-2_post_calving_habitat_suitability.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-postcalving-hsi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.2: Figure 5-2 – Finlayson Caribou Herd post-calving habitat suitability, home range and study area (BMC Appendix E-8, Part 17, November 2016).
</figcaption>
</figure>
</div>
<p>Across the FCH home range (~2,037,000 ha), the final HSI rasters were summarized into the six ordinal suitability classes and cross-tabulated against the independent aerial survey observation counts:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 5.1 – Habitat suitability results for the FCH home range (rut and post-calving)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Habitat suitability</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rut area (ha)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rut % of range</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Rut occurrences</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Post-calving area (ha)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Post-calving % of range</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Post-calving occurrences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nil</td>
<td style="text-align: right;">2,938</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">467,929</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Very low</td>
<td style="text-align: right;">631,895</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">1,012,818</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low</td>
<td style="text-align: right;">830,922</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">224,298</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate</td>
<td style="text-align: right;">213,789</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">102,307</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderately high</td>
<td style="text-align: right;">192,737</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">474</td>
<td style="text-align: right;">101,316</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">124</td>
</tr>
<tr class="even">
<td style="text-align: left;">High</td>
<td style="text-align: right;">164,978</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1,381</td>
<td style="text-align: right;">128,251</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">337</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsi_files/figure-html/hsi-results-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Occurrence density rises sharply with habitat suitability class, for both seasons</figcaption>
</figure>
</div>
</div>
</div>
<p>The proportion of observations climbs steeply through the higher suitability classes for both seasons — the <em>High</em> class contains only 8% of the rut range area but captures 65% of rut occurrences (1,381 of 2,124), and only 6% of the post-calving range area but captures 61% of post-calving occurrences (337 of 548) — supporting the models’ predictive validity.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 5.2 – Summary of direct and indirect Project effects on moderately-high to high suitability rut and post-calving habitat</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Rut</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Post-calving</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Moderately high–high suitability habitat in FCH range</td>
<td style="text-align: left;">357,715 ha (17%)</td>
<td style="text-align: left;">229,567 ha (11%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">...of which directly affected by Project footprint</td>
<td style="text-align: left;">777 ha (0.42%)</td>
<td style="text-align: left;">118 ha (0.12%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">...of which indirectly affected within LSA</td>
<td style="text-align: left;">4,771 ha (2.72%)</td>
<td style="text-align: left;">2,778 ha (2.39%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Directly affected as % of same-quality habitat within LSA</td>
<td style="text-align: left;">~15%</td>
<td style="text-align: left;">~4%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsi_files/figure-html/local-study-area-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Moderately-high/high suitability habitat: FCH range vs.&nbsp;directly/indirectly affected proportions</figcaption>
</figure>
</div>
</div>
</div>
<p>Within the LSA specifically, moderately-high and high suitability rut habitat was concentrated close to the Project footprint — where the direct footprint overlaps rut habitat, the impact reaches ~15% of the same-quality habitat available within the LSA, compared with only ~4% for post-calving habitat. Applying a 100 m focal-statistics smoothing pass to the raw suitability surface (Figure 4-2 of the original report) removed isolated single-cell artifacts and produced a more spatially coherent (and more conservative, in terms of contiguous suitable-habitat patches) representation of the landscape than the unsmoothed output.</p>
</section>
<section id="late-winter-habitat-suitability" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="late-winter-habitat-suitability"><span class="header-section-number">10.2</span> Late Winter Habitat Suitability</h2>
<div id="fig-latewinter-hsi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-latewinter-hsi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig5-1_late_winter_habitat_suitability.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-latewinter-hsi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.3: Figure 5-1 – Finlayson Caribou Herd late winter habitat suitability, home range (BMC KZK Response Report IR6, January 2018).
</figcaption>
</figure>
</div>
<p>The late-winter model, added in 2018 in response to a YESAB Adequacy Review request, covered the same ~2,036,800 ha FCH home range extent.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 5.3 – Late winter habitat suitability results for the FCH home range</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Habitat suitability</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Area (ha)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">% of FCH range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nil</td>
<td style="text-align: right;">198,867</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Very low</td>
<td style="text-align: right;">275,813</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low</td>
<td style="text-align: right;">370,714</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate</td>
<td style="text-align: right;">488,971</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderately high</td>
<td style="text-align: right;">431,098</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">High</td>
<td style="text-align: right;">271,315</td>
<td style="text-align: right;">13</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 5.4 – Late winter habitat directly and indirectly affected by the Project Access Road</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Habitat suitability</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Indirectly affected - LSA (ha)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Directly affected - Access Road (ha)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nil</td>
<td style="text-align: right;">1,601</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Very low</td>
<td style="text-align: right;">2,713</td>
<td style="text-align: right;">403</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low</td>
<td style="text-align: right;">2,975</td>
<td style="text-align: right;">456</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate</td>
<td style="text-align: right;">3,582</td>
<td style="text-align: right;">90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderately high</td>
<td style="text-align: right;">1,583</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">High</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hsi_files/figure-html/winter-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribution of late winter habitat suitability across the FCH home range</figcaption>
</figure>
</div>
</div>
</div>
<p>Unlike the rut and post-calving models — where suitable habitat is concentrated in a relatively small fraction of the range — late winter suitability is more evenly distributed, with moderately-high/high habitat covering 34% (702,413 ha) of the FCH range. Critically, <strong>no high-suitability late winter habitat occurs within the LSA</strong>, and the proposed mine footprint does not overlap any moderately-high or high-suitability late winter habitat at all — only the Access Road corridor intersects moderate (90 ha direct / 3,582 ha indirect) and moderately-high (11 ha direct / 1,583 ha indirect) winter habitat, representing less than 1% of all moderate-to-high suitability late winter habitat range-wide.</p>
</section>
</section>
<section id="discussion" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Discussion</h1>
<p>Taken together, the three HSI models indicate that:</p>
<ul>
<li>The <strong>LSA contains high-quality rut and post-calving habitat</strong>, and the proposed mine footprint and Access Road directly overlap a small but ecologically meaningful proportion (≤1% range-wide, but up to 15% of same-quality LSA habitat) of the highest-value habitat for these two seasons.</li>
<li>The <strong>LSA contains no high-quality late winter habitat</strong>, and the mine site itself has only low-to-nil winter suitability; only the Access Road corridor passes through moderate/moderately-high winter range, at a much smaller relative magnitude than the rut/post-calving effects.</li>
<li>All three models showed <strong>statistically significant, strong-to-very-strong correlations</strong> (Kendall’s tau 0.73–1.00, p &lt; 0.05) between predicted suitability class and independent aerial survey observation density, supporting their use as a defensible baseline for effects assessment.</li>
</ul>
<p>The resulting suitability maps and hectare/percentage tables were used to inform the design of avoidance and mitigation measures and to support the assessment of residual Project effects on caribou habitat, as required under the federal NMP Management Plan objectives.</p>
<p>Several factors are <strong>not captured</strong> by the HSI framework and should be considered when interpreting results:</p>
<ul>
<li>Year-to-year and inter-annual variability in weather, snowpack, and climate change are not reflected; the models represent a long-term average pattern of habitat selection rather than a single-year prediction.</li>
<li>Wildfire history and its effect on vegetation succession — and therefore on habitat suitability and caribou movement — is not incorporated into the vegetation cover layer.</li>
<li>The models are built from <em>presence-only</em> data; the absence of caribou in a given location was not used to inform suitability, which can bias suitability estimates toward locations that happened to be surveyed.</li>
<li>Positional accuracy varies substantially across the three input datasets (exact GPS fixes from satellite collars vs.&nbsp;~200 m accuracy for VHF and aerial survey data), which propagates uncertainty into the variable values assigned to each calibration point.</li>
<li>The HSI is a knowledge-based model that blends quantitative calibration data with expert opinion (e.g., weighting of aspect, treatment of rock/ice classes), and therefore carries some expert-derived bias.</li>
</ul>
</section>
<section id="limitations" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Limitations</h1>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Table 6.1 – Consolidated model limitations (rut/post-calving and late winter)</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">#</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Limitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Only a small subset of location points came from satellite collars (exact ground locations); remaining VHF and aerial survey data carry ~200 m positional accuracy, affecting the variable values extracted at each location.</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">The HSI is a knowledge-based model combining quantitative data with expert opinion, and therefore reflects some expert-opinion bias (e.g., variable weighting, categorical class rankings).</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Model accuracy is bounded by the accuracy of the original source data (DEM, PEM vegetation mapping, climate normals).</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">The model was built using presence-only data; absence of caribou at a location was not incorporated, which can bias suitability estimates.</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="references" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> References</h1>
<p>Adamczewski, J., R. Florkiewicz, R. Farnell, C. Foster, and K. Egli. (2010). <em>Finlayson caribou herd late-winter population survey, 2007.</em> Yukon Fish and Wildlife Branch Report SR-10-01. Whitehorse, Yukon, Canada.</p>
<p>Alexco Environmental Group (AEG). (2016). <em>Kudz Ze Kayah Project, Wildlife Baseline Report.</em> Submitted as Appendix E-8 of the Project Proposal for YESAB Executive Committee Screening.</p>
<p>Alexco Environmental Group (AEG). (2016). <em>Caribou Habitat Suitability Report, Kudz Ze Kayah Project.</em> BMC-15-01-845_026_Caribou Habitat Suitability Report_Rev0_161219. Prepared for BMC Minerals (No.&nbsp;1) Ltd.</p>
<p>Alexco Environmental Group (AEG). (2018). <em>Caribou Late Winter Habitat Suitability Report, Kudz Ze Kayah Project.</em> BMC-17_Caribou_Late_Winter_HS_Rev0_171219. Prepared for BMC Minerals (No.&nbsp;1) Ltd.</p>
<p>Bergerud, A. T., Jakimchuk, R. D., and D. R. Carruthers. (1984). The buffalo of the north: caribou (<em>Rangifer tarandus</em>) and human developments. <em>Arctic</em> 37:7–22.</p>
<p>Bergerud, A. T., and R. E. Page. (1987). Displacement and dispersion of parturient caribou at calving as antipredator tactics. <em>Canadian Journal of Zoology</em> 65:1597–1606.</p>
<p>BMC Minerals (No.&nbsp;1) Ltd.&nbsp;(2017). <em>Kudz Ze Kayah Project, Project Proposal for YESAB Executive Committee Screening.</em> March 2017.</p>
<p>BMC Minerals (No.&nbsp;1) Ltd.&nbsp;(2020). <em>Response Report #6 to YESAB Executive Committee Information Request, Kudz Ze Kayah Project Proposal.</em> July 2020.</p>
<p>Chisana Caribou Recovery Team. (2010). <em>Recovery of the Chisana Caribou Herd in the Alaska/Yukon Borderlands: Captive-Rearing Trials.</em> Yukon Fish and Wildlife Branch Report TR-10-02.</p>
<p>Cichowski, D. C. (1993). <em>Seasonal movements, habitat use, and winter feeding ecology of woodland caribou in west-central British Columbia.</em> B.C. Ministry of Forests, Victoria, B.C. Land Management Report No.&nbsp;79.</p>
<p>Clarke, H. (2012). <em>Knowledge-based habitat suitability modeling guidelines.</em> Whitehorse: Yukon Environment.</p>
<p>EDI Environmental Dynamics Inc.&nbsp;(2015). <em>Kudz Ze Kayah, Late Winter Ungulate Survey 2015.</em> Prepared for BMC Minerals Ltd.</p>
<p>Environment Canada. (2012a). <em>Management plan for the Northern Mountain Population of woodland caribou (Rangifer tarandus caribou) in Canada.</em> Species at Risk Act Management Plan Series. Ottawa.</p>
<p>Environment Canada. (2012b). <em>Recovery Strategy for the woodland caribou (Rangifer tarandus caribou), Boreal population, in Canada.</em> Species at Risk Act Recovery Strategy Series. Ottawa.</p>
<p>Farnell, R., and J. McDonald. (1989). The influence of wolf predation on caribou mortality in Yukon’s Finlayson caribou herd. <em>Proceedings of the 2nd North American Caribou Workshop.</em> Alaska Department of Fish and Game, Juneau. Wildlife Technical Bulletin No.&nbsp;8:52–70.</p>
<p>Fenger, M. A., Eastman, D. S., and C. J. Clement. (1986). <em>Caribou habitat use on the Level Mountain and Horseranch ranges, British Columbia.</em> Surveys and Resource Mapping Branch Working Report WR-8.</p>
<p>Gerhart, K. L., R. G. White, R. D. Cameron, and D. E. Russell. (1996). Growth and body composition of arctic caribou. <em>Rangifer</em> 16:393–394.</p>
<p>Grods, J., S. R. Francis, K. McKenna, J. C. Meikle, and S. Lapointe. (2013). <em>East-central broad ecosystems (Version 1.1).</em> Spatial data created for Energy, Mines and Resources, Government of Yukon by Makonis Consulting Ltd.&nbsp;and Associates, West Kelowna, BC.</p>
<p>Guisan, A., and N. Zimmermann. (2000). Predictive habitat distribution models in ecology. <em>Ecological Modelling</em> 135:147–186.</p>
<p>Ion, P. G., and G. P. Kershaw. (1989). The selection of snowpatches as relief habitat by woodland caribou (<em>Rangifer tarandus caribou</em>), MacMillan Pass, Selwyn/Mackenzie Mountains, N.W.T., Canada. <em>Arctic</em> 21(2):203–211.</p>
<p>Johnson, C. J., K. L. Parker, D. C. Heard, and D. R. Seip. (2004). Movements, foraging habits, and habitat use strategies of northern woodland caribou during winter: implications for forest practices in British Columbia. <em>BC Journal of Ecosystems and Management</em> 5(1):22–35.</p>
<p>Kuzyk, G. W., M. M. Dehn, and R. S. Farnell. (1999). Body size comparisons of alpine and forest wintering woodland caribou in Yukon. <em>Canadian Journal of Zoology</em> 77:1017–1024.</p>
<p>MacLean, N. (2003). <em>Species Account and Wildlife Habitat Suitability Model Assumptions: Woodland Caribou.</em> Prepared for the Ministry of Water, Land and Air Protection.</p>
<p>Morgan, T. (2015). <em>Finlayson Caribou Fall Composition Survey 2015.</em> Liard Regional Management, Environment Yukon, Watson Lake, Yukon.</p>
<p>Mörschel, F. M., and D. R. Klein. (1997). Effects of weather and parasitic insects on the behavior and group dynamics of caribou of the Delta herd, Alaska. <em>Canadian Journal of Zoology</em> 75:1659–1670.</p>
<p>Oosenbrug, S. M., and J. B. Theberge. (1980). Altitudinal movements and summer habitat preferences of woodland caribou (<em>Rangifer tarandus caribou</em>) in the Kluane Ranges, Yukon Territory, Canada. <em>Arctic</em> 33:59–72.</p>
<p>Parker, K. L., P. S. Barboza, and M. P. Gillingham. (2009). Nutrition integrates environmental responses of ungulates. <em>Functional Ecology</em> 23:57–69.</p>
<p>R Core Team. (2014). <em>R: A Language and Environment for Statistical Computing.</em> R Foundation for Statistical Computing, Vienna, Austria.</p>
<p>Resources Inventory Committee (RIC). (1999). <em>British Columbia wildlife habitat rating standards, version 2.0.</em> Ministry of Environment, Lands and Parks, Victoria, BC.</p>
<p>Russell, D. E., A. M. Martell, and W. A. C. Nixon. (1993). Range ecology of the Porcupine caribou herd in Canada. <em>Rangifer</em> Special Issue No.&nbsp;8.</p>
<p>Skoog, R. C. (1968). <em>Ecology of caribou (Rangifer tarandus granti) in Alaska.</em> Ph.D.&nbsp;Thesis, University of California, Berkeley.</p>
<p>Statistics Solutions. (2016). <em>Kendall’s Tau and Spearman’s Rank Correlation Coefficient.</em> Accessed October 17, 2016.</p>
<p>Stevenson, S. K., H. M. Armleder, M. J. Jull, D. G. King, E. L. Terry, B. N. McLellan, and K. N. Child. (1994). <em>Mountain caribou in managed forests: preliminary recommendations for managers.</em> BC Ministry of Forests.</p>
<p>Thomas, D. C., and D. R. Gray. (2002). <em>Status report on woodland caribou Rangifer tarandus caribou in Canada.</em> COSEWIC Assessment and Update Status Report. Committee on the Status of Endangered Wildlife in Canada, Ottawa.</p>
<p>Wahl, H. E., D. B. Fraser, R. C. Harvey, and J. B. Maxwell. (1987). <em>Climate of Yukon.</em> Environment Canada, Climatological Studies No.&nbsp;40, Ottawa.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./habitat.html" class="pagination-link" aria-label="Habitat requirements">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Habitat requirements</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./movement.html" class="pagination-link" aria-label="Seasonal movements">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Seasonal movements</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>